### ISSUE TITLE
スコアを更新する

### ISSUE THREAD

**Issue by SilCil** [kugimasa/TETORIEVER#2]
# 概要
## GOALの定義
- 駒を消した数に応じて'Score'の値を加算する

## タスク
- [x] GameEvent -> intを作成して消した駒の数(int)をイベントで受け取れるようにする
- [x] イベントで受け取った値に応じて'Score'を加算する
- [x] 必要に応じて'HighScore'の値を変更する

## 使用する「変数/イベントオブジェクト」
'Score', 'HighScore'

### 補足説明
HighScoreのセーブ機能は不要

**Comment by Aojilu** [comment]
報告（コミットのとこにも書いた）
・GameEventIntのOnCellDeletedを作成した 実際に駒を消すと呼ばれるようにはなっていない
・ハイスコアの初期化はゲーム開始時（！＝プレイ開始時）にしたいので未実装にした

感想
・シーンのコンフリクトを避けるためにメインシーンのコピーを作った場合、animatorはそのままなのでいじるとおそらくコンフリクトする。コンフリクトしたときの大変さは不明
・最初は、mainシーンとGameManagerのanimatorのコピーを作成してテストを行ったが、シーンのコピーなしでもデバッグできそうだった
どっちがいいorどっちでもいい？　
・受け渡し方とフォルダ構成について
今回は作成したもののprefabを用意して、scriptsの下に作ったものをprefabも含めてすべて入れた
どうするのかの方針を決めたいかも？　今回作成したものは、script,prefab,scene,(animatorのコピー)
prefabの置き場ぐらいはあってもよさそう

**Comment by Aojilu** [comment]
追加issue?的なもののメモ
・ハイスコアの初期化を行う
・駒が消えたときにOnCellDeletedを呼ぶ
