### ISSUE TITLE
キーボド入力で指定のコマブロックを選択できる

### ISSUE THREAD

**Issue by kugimasa** [kugimasa/TETORIEVER#3]
# 概要
## GOALの定義
- 4種類のコマブロックからキーボード入力で選択してカーソル位置に表示する

## タスク
- [x] コマブロックのUIを実装
- [x] キーボード入力で現在選択しているコマブロックを切り替える 

## 使用する「変数/イベントオブジェクト」
- `OnPieceChanged`

### 補足説明
- コマブロックの種類は4種類でOKです
- このタスクに着手する人にお任せします
- ランダム生成は #4

**Comment by Aojilu** [comment]
報告
OnPieceChanged→eventの発行はindexで行っている　範囲は0~3
上記に記載されていないものとして、OnInputRecieved、BoardWorldPositionを使用している
randaom生成部分（issue#4）との接合はHandPieceHolderが継承している、ISetPieceData.SetPieceDataを利用。Support_handPieceControllerを参考にする
Support_handPieceControllerは、ほかに簡易的な入力受付も行っているため最終的に外す（一応flagで反応をoffにできる）
感想
・BoardWorldPositionがあったため、カーソルに従って移動することの実装は非常に簡単だった。が、BoardWorldPositionは事前定義されたものではなくissue#1で追加で作られたものであるため、実装順序が逆だったら時間がかかりそう＆無駄になりそうだと思った
・issue#4との兼ね合いが不透明だった。Pieceの画面表示はこちらで行うっぽいのは理解できたが、画面表示のもとになるデータもこちらで定義することになるのでIssue4がこちらに依存するorそれぞれのデータをすり合わせする存在が必要っぽい
また、データの受け渡し方は未決定なので結合issueが必要そう
・やることが割と多かった。UIの実装も含まれていたため、駒の簡易オブジェクトの作成、UI用のprefabの調整、選んでいるピースの枠の色を変える処理の作成なども行った。ただし、1week中の1日の作業でこれだけやるなら多分可能な分量だと思った。所要時間は５時間程度。ただしinterface分離などをある程度しっかり行ったりしたため雑にやればもう少し早くできそう
