### ISSUE TITLE
駒ブロックのランダム生成ができる

### ISSUE THREAD

**Issue by Aojilu** [kugimasa/TETORIEVER#4]
# 概要
## GOALの定義
- 駒ブロックを登録できる（どんなコマが出るかの登録機能）
- ランダムで登録されている駒ブロックを返せる
- 現在保持している駒ブロックを取得できる（4種）

## 使用する「変数/イベントオブジェクト」
- `OnPiecePlaced`
- `OnInputRecieved` もしくは置いた駒がなんなのか取得できるもの

### 補足説明
- 駒を表示するのは別の機能で実装する #3

**Comment by SilCil** [comment]
#9 を新たに作成したので、こちらは閉じます。
close #4
